default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  min_messages: warning
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  prepared_statements: false
  variables:
    statement_timeout: <%= ENV.fetch("TTS_DEFAULT_DB_STATEMENT_TIMEOUT", "3s") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_NAME", "TTS_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_NAME", "TTS_test") %>

staging:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_NAME", "TTS_staging") %>
  pool: 25

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_NAME", "TTS_production") %>
  pool: 40
