name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      Z_LOCALES: "en-us:de-de"
      # Temporary switch to enable the mobile front end for testing.
      ENABLE_EXPERIMENTAL_MOBILE_FRONTEND: 'true'
      # Compile assets only once.
      CI_SKIP_ASSETS_PRECOMPILE: 'true'
      # Avoid unnecessary DB resets.
      CI_SKIP_DB_RESET: 'true'
    strategy:
      fail-fast: false
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [4]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v1

      - name: Install requirements
        run: |
          sudo apt-add-repository multiverse && sudo apt-get update
          sudo apt-get -yqq install postgresql libpq-dev libimlib2 libimlib2-dev
          sudo service postgresql start
          sudo -u postgres createuser --superuser "$USER"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.4'
          bundler-cache: true

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install yarn
        run: npm install -g yarn

      - name: Get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn install
        run:  |
          yarn install

      - name: Setup app
        env:
          RAILS_ENV: test
          POSTGRES_USER: tts_test
          POSTGRES_PASSWORD: ''
        run: |
          cp config/database/database.yml config/database.yml
          bundle exec rake assets:precompile
          bundle exec rake zammad:db:init

      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_USER: tts_test
          POSTGRES_PASSWORD: ''
        run: |
          bundle exec rspec spec
