name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      Z_LOCALES: "en-us:de-de"
      # Temporary switch to enable the mobile front end for testing.
      ENABLE_EXPERIMENTAL_MOBILE_FRONTEND: 'true'
      # Compile assets only once.
      CI_SKIP_ASSETS_PRECOMPILE: 'true'
      # Avoid unnecessary DB resets.
      CI_SKIP_DB_RESET: 'true'
    services:
      postgres:
        image: postgres:13
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USERNAME: tts_test
          POSTGRES_PASSWORD: ''
      redis:
        image: redis
        ports: ["6379:6379"]
      elasticsearch:
        image: elasticsearch:6.8.8
        ports: ["9200:9200"]
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.4'
          bundler-cache: true
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install yarn
        run: npm install -g yarn

      - name: Get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn install
        run: |
          yarn install

      - name: Setup app
        env:
          RAILS_ENV: test
          POSTGRES_USER: tts_test
          POSTGRES_PASSWORD: ''
        run: |
          cp config/database/database.yml config/database.yml
          bundle exec rake assets:precompile
          bundle exec rake zammad:db:init

      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_USER: tts_test
          POSTGRES_PASSWORD: ''
        run: |
          bundle exec rspec --exclude-pattern="spec/{system,integration}/**/*_spec.rb"
